- name: upgrade and  update packages
  become: true
  apt: 
   update_cache: yes

- name:  create backend dir
  file:
    path: ~/backend
    state: directory
     
- name: "unzip backend artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "install node dependencies"
  command: npm i 
  args:
    chdir: ~/backend

- name: Adding enviroment variable manual because it's not working, then start main.js
  shell: |
     cd ~/backend/dist
     export TYPEORM_CONNECTION=postgres
     export TYPEORM_ENTITIES=./modules/domain/**/*.entity.js
     export TYPEORM_MIGRATIONS_DIR='./migrations'
     export TYPEORM_HOST=udapeople-db.cmfinkhaadq0.us-east-1.rds.amazonaws.com
     export TYPEORM_PORT=5432
     export TYPEORM_USERNAME=postgres
     export TYPEORM_PASSWORD=postgres2022
     export TYPEORM_DATABASE=udadb
     pm2 start main.js
  register: execute_node

- name: print output
  debug:
    msg: "{{ execute_node.stdout_lines }}"