- name: upgrade and  update packages
  become: true
  apt: 
   update_cache: yes

- name:  create backend dir
  file:
    path: ~/backend
    state: directory
     
- name: "unzip backend artifact"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend

- name: "install node dependencies"
  command: npm i 
  args:
    chdir: ~/backend

- name: install and start app
  shell:  
    cd ~/backend/dist
    export TYPEORM_MIGRATIONS_DIR="./migrations"
    export TYPEORM_MIGRATIONS="./migrations/*.js"
    export TYPEORM_ENTITIES="./modules/domain/**/*.entity.js"
    pm2 stop default
    pm2 start main.js
  register: execute_node

- name: print output
  debug:
    msg: "{{ execute_node.stdout_lines }}"