global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - region: us-east-1
        access_key: 
        secret_key: 
        port: 9100
        filters:
         - name: tag:project
           values: [udapeople]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_public_dns_name]
        replacement: ${1}:9100
        target_label: __address__


global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'
scrape_configs:
  - job_name: 'prometheus'
    ec2_sd_configs:
      - region: us-east-1
        port: 9100
        filters:
          - name: tag:project
            values: [udapeople]
    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        target_label: instance
      - source_labels: [__meta_ec2_instance_id]
        target_label: instance_id
      - source_labels: [__meta_ec2_public_dns_name]
        target_label: public_dns_name

groups:
- name: AllInstances
  rules:
  - alert: UsingTooMuchMemory
    expr: node_memory_MemFree_bytes < 100000000
    for: 3m
    labels:
      severity: 'critical'
    annotations:
      title: 'Instace {{ $labels.instance }} is almost out of memory'
      description: '{{ $labels.instance }} of job {{ $labels.job }}  has been out of memory for 3 minutes'
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: 'critical'
    annotations:
      title: 'Instace {{ $labels.instance }} is Down'
      description: '{{ $labels.instance }} of job {{ $labels.job }}  is down for 1 minute'   




global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

  route:
    receiver: 'slack-notifications'

  receivers:
  - name: 'slack-notifications'
    slack_configs:
    - channel: '#monitor-infrastructures'
      send_resolved: true
      icon_url: https://avatars3.githubusercontent.com/u/3380462
      title: |-
        [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
        {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
          {{" "}}(
          {{- with .CommonLabels.Remove .GroupLabels.Names }}
            {{- range $index, $label := .SortedPairs -}}
              {{ if $index }}, {{ end }}
              {{- $label.Name }}="{{ $label.Value -}}"
            {{- end }}
          {{- end -}}
          )
        {{- end }}
      text: >-
        {{ range .Alerts -}}
         *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
         *Description:* {{ .Annotations.description }}
         *Details:*
           {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}